### ISSUE TITLE
Publication info not showing in completion pane.

### ISSUE THREAD

**Issue by stefanocoretta** [apcshields/autocomplete-bibtex#95] opened 2018-01-11 08:53 UTC
I realised recently that the completion pane is not showing the info of the entries anymore. I am not sure when this behaviour started. It used to work before. The `.bib` file has been created with bibDesk.

<img width="886" alt="screen shot 2018-01-11 at 09 44 00" src="https://user-images.githubusercontent.com/6429302/34816186-71e1b8fa-f6b4-11e7-96cf-bb88c93cb084.png">

I am running Atom 1.23.3, macOS 10.13.2 (17C88). Non-core packages:

```
autocomplete-awk@0.1.2
autocomplete-bibtex@1.1.0
document-outline@2.0.1
file-icons@2.1.15
insert-timestamp@0.2.4
language-awk@0.1.12
language-latex@1.1.1
language-literate@0.13.0
language-markdown@0.25.1
language-md-latex
language-praat@1.3.6
language-r@0.4.2
magic-reflow@0.3.0
markdown-preview-plus@2.4.16
minimap@4.29.7
pigments@0.40.2
script@3.17.3
sync-settings@0.8.3
teletype@0.5.0
wordcount@2.10.4
```

**Comment by mangecoeur** [comment] 2018-01-11 08:55
Can you paste a sample of the bibtex file? I made some changes to improve the performance of bibtex loading. The problem is, no two bibtex generators create the same format, so I might have introduced bugs for certain flavours.

Sent from Mail for Windows 10

From: Stefano Coretta
Sent: 11 January 2018 09:53
To: apcshields/autocomplete-bibtex
Cc: Subscribed
Subject: [apcshields/autocomplete-bibtex] Publication info not showing incompletion pane. (#95)

I realised recently that the completion pane is not showing the info of the entries anymore. I am not sure when this behaviour started. It used to work before. The .bib file has been created with bibDesk.

I am running Atom 1.23.3, macOS 10.13.2 (17C88). Non-core packages:
autocomplete-awk@0.1.2
autocomplete-bibtex@1.1.0
document-outline@2.0.1
file-icons@2.1.15
insert-timestamp@0.2.4
language-awk@0.1.12
language-latex@1.1.1
language-literate@0.13.0
language-markdown@0.25.1
language-md-latex
language-praat@1.3.6
language-r@0.4.2
magic-reflow@0.3.0
markdown-preview-plus@2.4.16
minimap@4.29.7
pigments@0.40.2
script@3.17.3
sync-settings@0.8.3
teletype@0.5.0
wordcount@2.10.4

**Comment by stefanocoretta** [comment] 2018-01-11 09:03
```
%% This BibTeX bibliography file was created using BibDesk.
%% http://bibdesk.sourceforge.net/

%% Created for Stefano Coretta at 2018-01-09 22:04:44 +0100 


%% Saved with string encoding Unicode (UTF-8) 



@misc{coretta2017,
	Author = {Stefano Coretta},
	Date-Added = {2018-01-07 19:41:04 +0000},
	Date-Modified = {2018-01-07 19:41:32 +0000},
	Howpublished = {Talk presented at Ultrafest VIII, 4 Oct, University of Potsdam, Germany.},
	Read = {1},
	Title = {Vowel duration and tongue root advancement in {I}talian and {P}olish},
	Year = {2017}}

@article{benguerel1980,
	Author = {Benguerel, Andr{\'e}-Pierre and Bhatia, Tej K.},
	Date-Added = {2018-01-05 16:10:27 +0000},
	Date-Modified = {2018-01-05 16:10:50 +0000},
	Isbn = {0031-8388},
	Journal = {Phonetica},
	Keywords = {phonology, descriptive, articulatory},
	Number = {3},
	Pages = {134--148},
	Publisher = {Karger Publishers},
	Read = {1},
	Title = {Hindi stop consonants: an acoustic and fiberscopic study},
	Ty = {JOUR},
	Volume = {37},
	Year = {1980},
	Bdsk-File-1 = {YnBsaXN0MDDUAQIDBAUGJCVYJHZlcnNpb25YJG9iamVjdHNZJGFyY2hpdmVyVCR0b3ASAAGGoKgHCBMUFRYaIVUkbnVsbNMJCgsMDxJXTlMua2V5c1pOUy5vYmplY3RzViRjbGFzc6INDoACgAOiEBGABIAFgAdccmVsYXRpdmVQYXRoWWFsaWFzRGF0YV8Qai4uLy4uLy4uL0xpYnJhcnkvYXJ0aWNsZS8xOTgwL0hpbmRpIHN0b3AgY29uc29uYW50cyBhbiBhY291c3RpYyBhbmQgZmliZXJzY29waWMgc3R1ZHkgKEJlbmd1ZXJlbCAxOTgwKS5wZGbSFwsYGVdOUy5kYXRhTxECZAAAAAACZAACAAAMTWFjaW50b3NoIEhEAAAAAAAAAAAAAAAAAAAAAAAAAEJEAAH/////H0hpbmRpIHN0b3AgY29uc29uYSNGRkZGRkZGRi5wZGYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAAAAwAEAAAKIGN1AAAAAAAAAAAAAAAAAAQxOTgwAAIAeS86VXNlcnM6U3RlZmFubzpEcm9wYm94OkxpYnJhcnk6YXJ0aWNsZToxOTgwOkhpbmRpIHN0b3AgY29uc29uYW50cyBhbiBhY291c3RpYyBhbmQgZmliZXJzY29waWMgc3R1ZHkgKEJlbmd1ZXJlbCAxOTgwKS5wZGYAAA4AmgBMAEgAaQBuAGQAaQAgAHMAdABvAHAAIABjAG8AbgBzAG8AbgBhAG4AdABzACAAYQBuACAAYQBjAG8AdQBzAHQAaQBjACAAYQBuAGQAIABmAGkAYgBlAHIAcwBjAG8AcABpAGMAIABzAHQAdQBkAHkAIAAoAEIAZQBuAGcAdQBlAHIAZQBsACAAMQA5ADgAMAApAC4AcABkAGYADwAaAAwATQBhAGMAaQBuAHQAbwBzAGgAIABIAEQAEgB3VXNlcnMvU3RlZmFuby9Ecm9wYm94L0xpYnJhcnkvYXJ0aWNsZS8xOTgwL0hpbmRpIHN0b3AgY29uc29uYW50cyBhbiBhY291c3RpYyBhbmQgZmliZXJzY29waWMgc3R1ZHkgKEJlbmd1ZXJlbCAxOTgwKS5wZGYAABMAAS8AABUAAgAO//8AAIAG0hscHR5aJGNsYXNzbmFtZVgkY2xhc3Nlc11OU011dGFibGVEYXRhox0fIFZOU0RhdGFYTlNPYmplY3TSGxwiI1xOU0RpY3Rpb25hcnmiIiBfEA9OU0tleWVkQXJjaGl2ZXLRJidUcm9vdIABAAgAEQAaACMALQAyADcAQABGAE0AVQBgAGcAagBsAG4AcQBzAHUAdwCEAI4A+wEAAQgDcANyA3cDggOLA5kDnQOkA60DsgO/A8ID1APXA9wAAAAAAAACAQAAAAAAAAAoAAAAAAAAAAAAAAAAAAAD3g==}}

@article{herbst2017,
	Author = {Herbst, Christian T. and Schutte, Harm K. and Bowling, Daniel L. and Svec, Jan G.},
	Date-Added = {2018-01-05 14:48:02 +0000},
	Date-Modified = {2018-01-05 14:48:37 +0000},
	Isbn = {0892-1997},
	Journal = {Journal of Voice},
	Keywords = {phonology, articulatory, methods},
	Number = {4},
	Pages = {401--409},
	Publisher = {Elsevier},
	Title = {Comparing chalk with cheese---the {EGG} contact quotient is only a limited surrogate of the closed quotient},
	To-Read = {1},
	Ty = {JOUR},
	Volume = {31},
	Year = {2017},
	Bdsk-File-1 = {YnBsaXN0MDDUAQIDBAUGJCVYJHZlcnNpb25YJG9iamVjdHNZJGFyY2hpdmVyVCR0b3ASAAGGoKgHCBMUFRYaIVUkbnVsbNMJCgsMDxJXTlMua2V5c1pOUy5vYmplY3RzViRjbGFzc6INDoACgAOiEBGABIAFgAdccmVsYXRpdmVQYXRoWWFsaWFzRGF0YW8QlwAuAC4ALwAuAC4ALwAuAC4ALwBMAGkAYgByAGEAcgB5AC8AYQByAHQAaQBjAGwAZQAvADIAMAAxADcALwBDAG8AbQBwAGEAcgBpAG4AZwAgAGMAaABhAGwAawAgAHcAaQB0AGgAIABjAGgAZQBlAHMAZSAUAHQAaABlACAARQBHAEcAIABjAG8AbgB0AGEAYwB0ACAAcQB1AG8AdABpAGUAbgB0ACAAaQBzACAAbwBuAGwAeQAgAGEAIABsAGkAbQBpAHQAZQBkACAAcwB1AHIAcgBvAGcAYQB0AGUAIABvAGYAIAB0AGgAZQAgAGMAbABvAHMAZQBkACAAcQB1AG8AdABpAGUAbgB0ACAAKABIAGUAcgBiAHMAdAAgADIAMAAxADcAKQAuAHAAZABm0hcLGBlXTlMuZGF0YU8RAxoAAAAAAxoAAgAADE1hY2ludG9zaCBIRAAAAAAAAAAAAAAAAAAAAAAAAABCRAAB/////x9Db21wYXJpbmcgY2hhbGsgd2kjRkZGRkZGRkYucGRmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAAAAMABAAACiBjdQAAAAAAAAAAAAAAAAAEMjAxNwACAKgvOlVzZXJzOlN0ZWZhbm86RHJvcGJveDpMaWJyYXJ5OmFydGljbGU6MjAxNzpDb21wYXJpbmcgY2hhbGsgd2l0aCBjaGVlc2XigJR0aGUgRUdHIGNvbnRhY3QgcXVvdGllbnQgaXMgb25seSBhIGxpbWl0ZWQgc3Vycm9nYXRlIG9mIHRoZSBjbG9zZWQgcXVvdGllbnQgKEhlcmJzdCAyMDE3KS5wZGYADgD0AHkAQwBvAG0AcABhAHIAaQBuAGcAIABjAGgAYQBsAGsAIAB3AGkAdABoACAAYwBoAGUAZQBzAGUgFAB0AGgAZQAgAEUARwBHACAAYwBvAG4AdABhAGMAdAAgAHEAdQBvAHQAaQBlAG4AdAAgAGkAcwAgAG8AbgBsAHkAIABhACAAbABpAG0AaQB0AGUAZAAgAHMAdQByAHIAbwBnAGEAdABlACAAbwBmACAAdABoAGUAIABjAGwAbwBzAGUAZAAgAHEAdQBvAHQAaQBlAG4AdAAgACgASABlAHIAYgBzAHQAIAAyADAAMQA3ACkALgBwAGQAZgAPABoADABNAGEAYwBpAG4AdABvAHMAaAAgAEgARAASAKZVc2Vycy9TdGVmYW5vL0Ryb3Bib3gvTGlicmFyeS9hcnRpY2xlLzIwMTcvQ29tcGFyaW5nIGNoYWxrIHdpdGggY2hlZXNl4oCUdGhlIEVHRyBjb250YWN0IHF1b3RpZW50IGlzIG9ubHkgYSBsaW1pdGVkIHN1cnJvZ2F0ZSBvZiB0aGUgY2xvc2VkIHF1b3RpZW50IChIZXJic3QgMjAxNykucGRmABMAAS8AABUAAgAO//8AAIAG0hscHR5aJGNsYXNzbmFtZVgkY2xhc3Nlc11OU011dGFibGVEYXRhox0fIFZOU0RhdGFYTlNPYmplY3TSGxwiI1xOU0RpY3Rpb25hcnmiIiBfEA9OU0tleWVkQXJjaGl2ZXLRJidUcm9vdIABAAgAEQAaACMALQAyADcAQABGAE0AVQBgAGcAagBsAG4AcQBzAHUAdwCEAI4BvwHEAcwE6gTsBPEE/AUFBRMFFwUeBScFLAU5BTwFTgVRBVYAAAAAAAACAQAAAAAAAAAoAAAAAAAAAAAAAAAAAAAFWA==}}

@article{bennett2017,
	Author = {Bennett, Wm. G. and Rose, Sharon},
	Date-Added = {2017-12-31 11:29:00 +0000},
	Date-Modified = {2017-12-31 11:29:45 +0000},
	Isbn = {0952-6757},
	Journal = {Phonology},
	Keywords = {phonology, descriptive, metatheory},
	Number = {3},
	Pages = {473--505},
	Publisher = {Cambridge University Press},
	Read = {1},
	Title = {Moro voicelessness dissimilation and binary [voice]},
	Ty = {JOUR},
	Volume = {34},
	Year = {2017},
	Bdsk-File-1 = {YnBsaXN0MDDUAQIDBAUGJCVYJHZlcnNpb25YJG9iamVjdHNZJGFyY2hpdmVyVCR0b3ASAAGGoKgHCBMUFRYaIVUkbnVsbNMJCgsMDxJXTlMua2V5c1pOUy5vYmplY3RzViRjbGFzc6INDoACgAOiEBGABIAFgAdccmVsYXRpdmVQYXRoWWFsaWFzRGF0YV8QZC4uLy4uLy4uL0xpYnJhcnkvYXJ0aWNsZS8yMDE3L01vcm8gdm9pY2VsZXNzbmVzcyBkaXNzaW1pbGF0aW9uIGFuZCBiaW5hcnkgW3ZvaWNlXSAoQmVubmV0dCAyMDE3KS5wZGbSFwsYGVdOUy5kYXRhTxECTAAAAAACTAACAAAMTWFjaW50b3NoIEhEAAAAAAAAAAAAAAAAAAAAAAAAAEJEAAH/////H01vcm8gdm9pY2VsZXNzbmVzcyNGRkZGRkZGRi5wZGYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAAAAwAEAAAKIGN1AAAAAAAAAAAAAAAAAAQyMDE3AAIAcy86VXNlcnM6U3RlZmFubzpEcm9wYm94OkxpYnJhcnk6YXJ0aWNsZToyMDE3Ok1vcm8gdm9pY2VsZXNzbmVzcyBkaXNzaW1pbGF0aW9uIGFuZCBiaW5hcnkgW3ZvaWNlXSAoQmVubmV0dCAyMDE3KS5wZGYAAA4AjgBGAE0AbwByAG8AIAB2AG8AaQBjAGUAbABlAHMAcwBuAGUAcwBzACAAZABpAHMAcwBpAG0AaQBsAGEAdABpAG8AbgAgAGEAbgBkACAAYgBpAG4AYQByAHkAIABbAHYAbwBpAGMAZQBdACAAKABCAGUAbgBuAGUAdAB0ACAAMgAwADEANwApAC4AcABkAGYADwAaAAwATQBhAGMAaQBuAHQAbwBzAGgAIABIAEQAEgBxVXNlcnMvU3RlZmFuby9Ecm9wYm94L0xpYnJhcnkvYXJ0aWNsZS8yMDE3L01vcm8gdm9pY2VsZXNzbmVzcyBkaXNzaW1pbGF0aW9uIGFuZCBiaW5hcnkgW3ZvaWNlXSAoQmVubmV0dCAyMDE3KS5wZGYAABMAAS8AABUAAgAO//8AAIAG0hscHR5aJGNsYXNzbmFtZVgkY2xhc3Nlc11OU011dGFibGVEYXRhox0fIFZOU0RhdGFYTlNPYmplY3TSGxwiI1xOU0RpY3Rpb25hcnmiIiBfEA9OU0tleWVkQXJjaGl2ZXLRJidUcm9vdIABAAgAEQAaACMALQAyADcAQABGAE0AVQBgAGcAagBsAG4AcQBzAHUAdwCEAI4A9QD6AQIDUgNUA1kDZANtA3sDfwOGA48DlAOhA6QDtgO5A74AAAAAAAACAQAAAAAAAAAoAAAAAAAAAAAAAAAAAAADwA==}}

@comment{BibDesk Static Groups{
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<dict>
		<key>group name</key>
		<string>2017-Ultrafest</string>
		<key>keys</key>
		<string>strycharczuk2015,scobbie2011,articulate2011,keating1984,farnetani1986,halle1967,westbury1983,ahn2015</string>
	</dict>
	<dict>
		<key>group name</key>
		<string>Cheke Holo</string>
		<key>keys</key>
		<string>boswell2011,lynch2002a,palmer2009,lynch2000,terrill2003,palmer2009a,blust2009,palmer1999,boswell2002,ridouane2011,boswell2001,gabelentz1873,white1988,woodford1890,kennedy2008,ross1988,white1995,tryon1983,ray1926,codrington1885,francois2011,bosma1981,francois2010,ohala2001,blevins2005,ivens1933,blevins2003,blevins2012a,ozanne-rivierre1992,lichtenberk1979,lynch1998</string>
	</dict>
	<dict>
		<key>group name</key>
		<string>Cluster</string>
		<key>keys</key>
		<string>maddieson1990,steriade1994,kadenge2010,kaye1985,chitoran1998,golston1998,francois2010,maddieson1989</string>
	</dict>
	<dict>
		<key>group name</key>
		<string>Dynamic System</string>
		<key>keys</key>
		<string>torre2014,thelen1996,thelen2006,poeppel2012</string>
	</dict>
	<dict>
		<key>group name</key>
		<string>EGG</string>
		<key>keys</key>
		<string>fabre1957,scherer1987,titze1990,herbst2010,herbst2014,hampala2016,belhaj2010,tang2015,macerata2016,herbst2017</string>
	</dict>
	<dict>
		<key>group name</key>
		<string>Emergent</string>
		<key>keys</key>
		<string>mithun2010,christiansen2015,thompson2016,kirby2002,oudeyer2006,boer2015,culbertson2015,soskuthy2017a,soskuthy2015,bentz2014,ernestus2003,cristofaro2012,cristofaro2014,cristofaro2015,wedel2007,wedel2011,thelen1996,thelen2006,pullum2002,port2005,tomasello2009,evans2009,blevins2009,anderson2016,morley2008,morley2015a,sen2016,christiansen2017,ellis2009,arnold2017,torre2014</string>
	</dict>
	<dict>
		<key>group name</key>
		<string>ESHIPH</string>
		<key>keys</key>
		<string>hintzman1986,nosofsky1988,hay2015,bybee2002a,wood2006,zuur2012</string>
	</dict>
	<dict>
		<key>group name</key>
		<string>Exemplar Theory</string>
		<key>keys</key>
		<string>ernestus2003,ernestus2006,ernestus2006a,nosofsky1988,hintzman1986,johnson1997,soskuthy2017a,strycharczuk2017,poeppel2012,soskuthy2015a,lavie2007,christiansen2017,schweitzer2004,delong2005</string>
	</dict>
	<dict>
		<key>group name</key>
		<string>Laryngeal</string>
		<key>keys</key>
		<string>demolin2002,weigelt1990,wyatt1964,halle2002,kehrein2002,dilley1996,silverman1997,kim1970,moisik2011,vaux1998,gordon2001a,howe2001,bhaskararao1991,gordeeva2007,chang2007,iverson1983,jacques2011,greenberg1970,palmer1999,lisker1986,jansen2004,elias-ulloa2009,ratliff2001,steriade1993,matisoff1975,silverman2012,silverman2003,parker1996,weijer2005,sprigg1987,stenzel2007,hall2001,craioveanu2013,lombardi1995,gandour1975,abramson1977,kehrein2004,ladefoged1973,gordon2001,bombien2006,lombardi1991,rich1963,lloret1995,benguerel1980,kagaya1975</string>
	</dict>
	<dict>
		<key>group name</key>
		<string>MA</string>
		<key>keys</key>
		<string>whalen1989,hombert1976,berg2001,simpson2005,port1979,blankenship2002,shrivastav2003,booij1986,hoole2006,house1953,blevins1993,belasco1953,javkin1976,davis1989,maddieson1976a,chen1970,iosad2012,prieto2000,maddieson1976,allen1978,hansson2003,hussein1994,durvasula2012,esposito2002,helgason1999,patil2016,carlson1990,hoole2010,kluender1988,gussmann2002,jones2003,khan2012,nance2013,jones2006,clayton2010,sancier1997,jessen1998,bombien2006,silverman1997,maddieson2012,ohala1983,lampp2004,blevins2004a,laeufer1992,fintoft1961,elert1970</string>
	</dict>
	<dict>
		<key>group name</key>
		<string>Manchester</string>
		<key>keys</key>
		<string>hall2005,loporcaro2009,unesco2016,onosson2010,haspelmath2010b,torres-tamarit2015,gick2005,miller2011,house1953,javkin1976,belasco1953,gick2002,chen1970,iosad2012,soskuthy2013,evans2009,prieto2000,maddieson1976,sanga1988,repetti2000,posner2004,strycharczuk2012,hussein1994,durvasula2012,grimaldi2008,tang2015,kluender1988,ramsammy2012,herbst2010,turton2014</string>
	</dict>
	<dict>
		<key>group name</key>
		<string>Mawayana</string>
		<key>keys</key>
		<string>de-jong2009</string>
	</dict>
	<dict>
		<key>group name</key>
		<string>Nominalization</string>
		<key>keys</key>
		<string>sprigg1987,blevins1993,ohala1977,jacques2011,recasens2011,michaud2012,white1988,michailovsky1975,igartua2011,howe2004,white1995,matisoff1975,igartua2015</string>
	</dict>
	<dict>
		<key>group name</key>
		<string>PhD</string>
		<key>keys</key>
		<string>granstrom1992,berkson2012,dalola2015,durvasula2012,pind1995,garnes1974,harbert2006,silverman1997,maddieson1976,arnason2011,rothenberg2009,kingston1987,konig2013,soskuthy2013,yao2009,ernestus2006,jansen2004,bybee1999,gahl2008,house1953,cho1999,helgason2002,pind1999,silverman2012,davis1995,silverman2003,petursson1981,ohala1992a,hussein1994,chen1970,dev2009,jessen1998,pind1993,thraisson1978,nichasaide1985,pind1982,esposito2002,farnetani1986,celata2014,iosad2016,klatt1973,bombien2013,rothenberg1988,titze1990,scherer1987,hampala2016,gick2002,gick2005,grimaldi2008,miller2011,ardestani2013,halle1967,fowler1992,goldstein1986,strycharczuk2015,hajek2008,davidson2006,bressmann2016,davidson2016,shih1999,koenig2011,herbst2010,belhaj2010,macerata2016,renwick2016,bigi2015,youngblood2007,rodgers2010,kim2015a,kim2015,dicanio2012,lofqvist2002,tasko2002,heyde2016,tasko2004,kroos1997,gafos2010,gafos2010a,fuchs2001,hermes2013,ananthapadmanabha2014,he2016,soskuthy2015,keating1984,malisz2008,moslin1977,hoole2014,lisker1974,toivonen2015,francis2003,scobbie2011,wood2006,soskuthy2017,ahn2016,ahn2015,westbury1983,kroch1989,bermudez-otero2016,lehiste1970,kagaya1975,henrich2004,abramson2017,baranowski2016,vazquez-alvarez2007,stevens2014a,stevens2004,stevens2010a,kirkham2015,strycharczuk2017,cresci2014,jacobs2017,heyne2015,chen2011,stevens2004a,stevens2010b,strycharczuk2017a,hanson2009,hanson2004,gordeeva2011,mortensen2013,santen1999,kirby2016,scheer2017,hirose1977,peterson1960,perkell1969,kent1969,epstein2005,fulop1998,kingston1997,jackson1988,kuznetsova2016,zharkova2009,ahn2016a,zuur2012,ohala2011,sproat1993,campos-astorkiza2007,kim2018,pape2014,herbst2017,benguerel1980</string>
	</dict>
	<dict>
		<key>group name</key>
		<string>Poster</string>
		<key>keys</key>
		<string>maddieson1976,durvasula2012,halle1967,peirce2009,nichasaide1985,hejna2015a,hejna2015,boersma2016,klatt1973,fowler1992,westbury1983,ohala2011,farnetani1986</string>
	</dict>
	<dict>
		<key>group name</key>
		<string>Reading list</string>
		<key>keys</key>
		<string>bigi2015</string>
	</dict>
	<dict>
		<key>group name</key>
		<string>Reproducibility</string>
		<key>keys</key>
		<string>knuth1984,buckheit1995,weigel2002,peng2009,maxwell2013,mahlow2011,maxwell2005,bird2003,thieberger2004,xie2014,sandve2013,abari2012,mcdonnell2017,fomel2009,blevins2004a,weigel2005,gawne2017,cysouw2015,wickham2014</string>
	</dict>
</array>
</plist>
}}

@comment{BibDesk Smart Groups{
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<dict>
		<key>conditions</key>
		<array>
			<dict>
				<key>comparison</key>
				<integer>3</integer>
				<key>key</key>
				<string>Date-Added</string>
				<key>value</key>
				<string></string>
				<key>version</key>
				<string>1</string>
			</dict>
		</array>
		<key>conjunction</key>
		<integer>0</integer>
		<key>group name</key>
		<string>Last week</string>
	</dict>
	<dict>
		<key>conditions</key>
		<array>
			<dict>
				<key>comparison</key>
				<integer>2</integer>
				<key>key</key>
				<string>Local File</string>
				<key>value</key>
				<string>0</string>
				<key>version</key>
				<string>1</string>
			</dict>
		</array>
		<key>conjunction</key>
		<integer>0</integer>
		<key>group name</key>
		<string>Local files</string>
	</dict>
	<dict>
		<key>conditions</key>
		<array>
			<dict>
				<key>comparison</key>
				<integer>4</integer>
				<key>key</key>
				<string>Read</string>
				<key>value</key>
				<string>1</string>
				<key>version</key>
				<string>1</string>
			</dict>
		</array>
		<key>conjunction</key>
		<integer>0</integer>
		<key>group name</key>
		<string>Read</string>
	</dict>
	<dict>
		<key>conditions</key>
		<array>
			<dict>
				<key>comparison</key>
				<integer>5</integer>
				<key>key</key>
				<string>Date-Added</string>
				<key>value</key>
				<string>30 1</string>
				<key>version</key>
				<string>1</string>
			</dict>
		</array>
		<key>conjunction</key>
		<integer>0</integer>
		<key>group name</key>
		<string>This month</string>
	</dict>
	<dict>
		<key>conditions</key>
		<array>
			<dict>
				<key>comparison</key>
				<integer>2</integer>
				<key>key</key>
				<string>Date-Added</string>
				<key>value</key>
				<string></string>
				<key>version</key>
				<string>1</string>
			</dict>
		</array>
		<key>conjunction</key>
		<integer>0</integer>
		<key>group name</key>
		<string>This week</string>
	</dict>
	<dict>
		<key>conditions</key>
		<array>
			<dict>
				<key>comparison</key>
				<integer>4</integer>
				<key>key</key>
				<string>To-Read</string>
				<key>value</key>
				<string>1</string>
				<key>version</key>
				<string>1</string>
			</dict>
		</array>
		<key>conjunction</key>
		<integer>0</integer>
		<key>group name</key>
		<string>To read</string>
	</dict>
	<dict>
		<key>conditions</key>
		<array>
			<dict>
				<key>comparison</key>
				<integer>0</integer>
				<key>key</key>
				<string>Date-Added</string>
				<key>value</key>
				<string></string>
				<key>version</key>
				<string>1</string>
			</dict>
		</array>
		<key>conjunction</key>
		<integer>0</integer>
		<key>group name</key>
		<string>Today</string>
	</dict>
	<dict>
		<key>conditions</key>
		<array>
			<dict>
				<key>comparison</key>
				<integer>1</integer>
				<key>key</key>
				<string>Date-Added</string>
				<key>value</key>
				<string></string>
				<key>version</key>
				<string>1</string>
			</dict>
		</array>
		<key>conjunction</key>
		<integer>0</integer>
		<key>group name</key>
		<string>Yesterday</string>
	</dict>
</array>
</plist>
}}
```

**Comment by mangecoeur** [comment] 2018-01-11 09:06
Thanks, I will try and see if I can fix this without breaking something else (for reference, the file metadata does work when using the Bibtex generated by Mendeley). 

Sent from Mail for Windows 10

**Comment by Juan4** [comment] 2018-01-11 17:32
Just to say that I have the same issue, also with Bibdesk.

**Comment by mangecoeur** [comment] 2018-02-08 21:55
I tested the latest release with this example and it seems to work fine, will close the issue for now let me know if it is fixed for you

**Closed by mangecoeur** 2018-02-08 21:55 UTC
